/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить агрегированные позитивные новости */
        get: {
            parameters: {
                query?: {
                    sources?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список позитивных новостей */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NewsListResponse"];
                    };
                };
                /** @description Невалидный параметр sources */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить новость по id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Данные новости */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NewsItem"];
                    };
                };
                /** @description Новость не найдена */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отправить отзыв */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FeedbackPayload"];
                };
            };
            responses: {
                /** @description Принято */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeedbackResponse"];
                    };
                };
                /** @description Ошибка валидации (message < 10 символов) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NewsItem: {
            /** @example technology/2025/jan/01/news-title */
            id: string;
            /** @example Scientists discover new renewable energy source */
            title: string;
            /** @example A breakthrough in solar panel efficiency... */
            description: string;
            /** @example https://media.guardian.co.uk/image.jpg */
            image: string;
            /** @example 2025-01-01T12:00:00Z */
            published: string;
            /** @example Jane Smith */
            author: string;
            /** @example Technology */
            tag: string;
            /**
             * @example guardian
             * @enum {string}
             */
            source: "guardian" | "newsapi" | "hackernews";
        };
        NewsListResponse: {
            news: components["schemas"]["NewsItem"][];
            /**
             * @example {
             *       "guardian": "ok",
             *       "newsapi": "skipped",
             *       "hackernews": "ok"
             *     }
             */
            sources: {
                [key: string]: "ok" | "error" | "skipped";
            };
            /** @example false */
            cached: boolean;
        };
        FeedbackPayload: {
            /** @example Отличный сайт, очень позитивно! */
            message: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email?: string;
        };
        FeedbackResponse: {
            /** @example true */
            ok: boolean;
            /** @example Спасибо за отзыв! */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
